### ISSUE TITLE
Max all does not fully max all; it only buys 10% of each dimension per proc.

### ISSUE THREAD

**Issue by James103** [HexaVault/AD-breaketernity#11]
**Describe the bug**
Max all does not fully purchase all affordable upgrades for every dimension. Only 10% of the affordable upgrades are purchased every iteration.

**To Reproduce**
1. Start a new save.
2. `dev.beTests.speed()`
3. Buy 1st Antimatter Dimension once.
4. Max all a few times.
5. Notice max all doesn't buy the full affordable amount every time it is pressed.

In vanilla: 1st AD purchased amount goes 1, 90, 370, 510, 580, 610, 630, 640 before slowing down.
In BE: 1st AD purchased amount goes 1, 17, 52, 97, 135, 174, 212, 250, 286, 314, 344, 371, 399, 419, 437, 456, 475, 494, 513, 531, 550, 569, 579, 588, 598, 607, 617, 626, 636, 645 before slowing down. From this, it takes many more M presses to reach the same purchased amount. This also shows max all buying singles, which should not happen if a full set is affordable.

**Expected behavior**
Max all should buy the full affordable amount of every dimension, instead of 10%.
This is the case in vanilla AD, where I tested by forcing game speed to be `1e24`.

**Comment by HexaVault** [comment]
seems my dumbass probably forgot to shove a .floor _before_ the purchasesPerIncrease multiplier. Easy fix, just remember to not floor if roundDown is false (math.js, exponential cost scaling)

**Comment by HexaVault** [comment]
oh yeah, there's also the less important "can't buy a singular ad" bug, which I'll shove w/ this since they both are relatively easy fixes

**Comment by HexaVault** [comment]
See issue #12
