### ISSUE TITLE
Can't locally test the game - `adnot-beport-large` module not found

### ISSUE THREAD

**Issue by James103** [HexaVault/AD-breaketernity#13]
**Describe the bug**
When running `npm run serve`, I get the following error:
```
ERROR in ./src/core/notations.js 2:0-51
Module not found: Error: Can't resolve 'adnot-beport-large' in '...\AD-breaketernity\src\core'
 @ ./src/core/globals.js 14:0-28 14:0-28
 @ ./src/merge-globals.js 35:0-39 36:16-20
 @ ./src/main.js 4:0-25
```

Caused by 4949fd2e12ef4ec5cce170a18c500dc4e89949d2 (found with `git bisect`)

**To Reproduce**
Run `npm run serve`

**Expected behavior**
`npm run serve` should compile successfully and allow the game to be opened in a browser.

<details>

<summary> <code>npm version</code> output </summary>

```
{
  npm: '10.4.0',
  node: '20.11.1',
  acorn: '8.11.2',
  ada: '2.7.4',
  ares: '1.20.1',
  base64: '0.5.1',
  brotli: '1.0.9',
  cjs_module_lexer: '1.2.2',
  cldr: '43.1',
  icu: '73.2',
  llhttp: '8.1.1',
  modules: '115',
  napi: '9',
  nghttp2: '1.58.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.13+quic',
  simdutf: '4.0.4',
  tz: '2023c',
  undici: '5.28.3',
  unicode: '15.0',
  uv: '1.46.0',
  uvwasi: '0.0.19',
  v8: '11.3.244.8-node.17',
  zlib: '1.2.13.1-motley-5daffc7'
}
```

</details>

**Comment by Donaldino7712** [comment]
from the ad discord server:
![image](https://github.com/HexaVault/AD-breaketernity/assets/100215778/9c7fbe54-691f-4550-b641-8dd6ab8c7011)
this is something that @HexaVault has to fix in the package itself

**Comment by Donaldino7712** [comment]
so as it turns out, the package has been updated with the fix, however we still use the older version

**Comment by Donaldino7712** [comment]
should be fixed in https://github.com/HexaVault/AD-breaketernity/commit/0577f074f034eadb1270479136444bc50325fc17
