### ISSUE TITLE
Royal's bug hunting session

### ISSUE THREAD

**Issue by toilet45** [HexaVault/AD-breaketernity#15]
- the Big Crunch popup in classic UI throws vue errors (change line 39 in ClassicUI.vue to .gt(1))
- similar thing happens with the eternity button with at least 1 eternity (change line 141 to Currency.eternityPoints.value)
- DarkMatterDimensions.reset() goes out of bounds (tries to reset DMD5+)

have yet to test reality stuff

**Comment by Donaldino7712** [comment]
we haven't touched classic ui _at all_

**Comment by toilet45** [comment]
forgot about r62. bestRunIPPM doesn't seem to go above e-7 (yes I messed with dev.speedUp, but even around eternity it won't go above e-7 [e6 speedup])

**Comment by toilet45** [comment]
UPDATE: it seems to update from its default value of (e^8999999999999998)-10000000000, so it stops updating a a certain point?

**Comment by toilet45** [comment]
might've found it

line 60 of cache.js

    player.records.recentInfinities
      .map(run => run[3].div(run[1].times(60000)))
      .reduce(Decimal.maxReducer)
  ),

run[3] is always 1, so maybe an off by 1?

**Comment by HexaVault** [comment]
afaik all fixed, closing
