### ISSUE TITLE
Tickspeed Upgrades from Time Shards asymptotically hardcap in a way not present in vanilla AD

### ISSUE THREAD

**Issue by James103** [HexaVault/AD-breaketernity#16]
**Describe the bug**
Tickspeed Upgrades gained from Time Shards appear to asymptotically approach a hardcap shortly after the softcap, such that as the amount of Time Shards approaches infinity, the corresponding number of Tickspeed Upgrades approach a value a few hundred upgrades above the softcap. For example, a softcap of 300,000 Tickspeed Upgrades leads to a hardcap of 300,475.

This breaks balance after Celestial 1 because players will be lacking the Tickspeed necessary to push for higher RM.

In BE port:
> You have gained 300,475 Tickspeed upgrades from 1e1.000e12 Time Shards. Next Tickspeed upgrade at 5.51e37214, increasing by ×1.33 per Tickspeed upgrade gained. 

In vanilla:
> You have gained 876,339,416 Tickspeed upgrades from 1.00e1.000e12 Time Shards. Next Tickspeed upgrade at 9.47e1.000e12, increasing by ×7.56e2282 per Tickspeed upgrade gained.

**To Reproduce**
Do any one of the following (from least to most time consuming)
A:
1. Run this command: `FreeTickspeed.fromShards(new Decimal("1e1000000000000"))`
2. Notice the value on `newAmount` is somewhere around 300,475 in the BE port versus 876 million in vanilla.

B:
1. Get to Eternity.
2. Run this command: `player.timeShards = new Decimal("1e1000000000000")`
3. Check the Time Dimensions tab and notice it says "You have gained 300,475 Tickspeed upgrades" in the BE port versus "You have gained 876,339,416 Tickspeed upgrades" in vanilla.

C: 
1. Get to Reality, and ideally at least 1e14-1e18 RM, Celestial 1 completed, and high rarity GL600 Time and Dilation glyphs.
2. Push Time Shards as much as you can in a single Reality.
3. Check the Time Dimensions tab and notice the Tickspeed Upgrade amount increase slow down harshly. The value of X in "next Tickspeed Upgrade at X" becomes much smaller than the actual number of Tickspeed Upgrades.

**Expected behavior**
Tickspeed Upgrades from Time Shards should scale similarly to that of vanilla, with one being able to achieve millions of Tickspeed Upgrades from Time Shards by the end.

**Comment by HexaVault** [comment]
known, currently working on fixing export/import errors from be to be, then focus will be put on this

**Comment by HexaVault** [comment]
patched a while ago, forgot to close, closing
