### ISSUE TITLE
Error in glyph uniformity code prevents Realitying for the first time

### ISSUE THREAD

**Issue by James103** [HexaVault/AD-breaketernity#22]
**Describe the bug**
It looks like the glyph uniformity code is broken when one is trying to perform the very first reality, making it effectively impossible to actually perform said reality.
https://github.com/HexaVault/AD-breaketernity/blob/c77a46927fc8e60728e012a3ae043249a7619ec7/src/core/glyphs/glyph-generator.js#L332

Stack trace:
```
18:48:43.534 TypeError: GlyphInfo[glyphsChosen[i]].effects()[groupIndex] is undefined
    uniformGlyphSelections glyph-generator.js:332
    glyphList reality.js:49
    get upcomingGlyphs reality.js:110
    refreshGlyphs GlyphPeek.vue:35
    created GlyphPeek.vue:20
    VueJS 44
    sortModalQueue modal.js:152
    show modal.js:120
    show modal.js:348
    purchase dilation-time-study.js:51
    handleClick TimeStudyButton.vue:157
    click TimeStudyButton.vue:19
    VueJS 33
vue.runtime.esm.js:3065
```

**To Reproduce**
Unlock Reality by purchasing the Reality Study for the first time. This takes the player to the Reality tab and Glyphs subtab, which breaks due to the above-mentioned error.

**Expected behavior**
One should be able to unlock and perform a Reality for the first time, which should give an uncommon Power glyph.

**Savefile**
To speed up reproduction: import this save and Eternity first.
[save.txt](https://github.com/user-attachments/files/16241412/save.txt)

**Comment by HexaVault** [comment]
Will be fixed when i update (so sometime in the next couple hours) -- closing
