### ISSUE TITLE
Something is increasing the base purchase hardcap for Infinity Dimensions over time (while on that tab)

### ISSUE THREAD

**Issue by James103** [HexaVault/AD-breaketernity#23]
**Describe the bug**
When the Infinity Dimensions tab is open and at least one Tesseract is bought, every tick, each Infinity Dimension that is capped on purchases causes the _base hardcap_ on said purchase amount to increase by the bonus given to that hardcap from Tesseracts.

For example, if the first Tesseract is bought and the first Infinity Dimension is capped on purchases, then the base hardcap for Infinity Dimension purchases increases by 500,000 every tick until the first Infinity Dimension is no longer capped on purchases.

**To Reproduce**
Purchase at least one Tesseract and cap any Infinity Dimension on purchases. Then watch the purchase cap increase until no Infinity Dimension meets it.

**Expected behavior**
The base hardcap on Infinity Dimension purchases should remain the same.

**Screenshots**
Originally found in Doomed Reality, here:
![image](https://github.com/user-attachments/assets/20e8a50b-9474-43ef-a63d-35593d975ce0)

**Most likely cause**
The `InfinityDimensionRow` components initialize their local `hardcap` variables with `InfinityDimensions.HARDCAP_PURCHASES` here:
https://github.com/HexaVault/AD-breaketernity/blob/c77a46927fc8e60728e012a3ae043249a7619ec7/src/components/tabs/infinity-dimensions/ModernInfinityDimensionRow.vue#L36

Then, if `this.isCapped` is true, meaning an Infinity Dimension is capped on purchases, `this.hardcap.copyFrom(dimension.purchaseCap)` is called, which updates the local `hardcap` variable with the new cap.
https://github.com/HexaVault/AD-breaketernity/blob/c77a46927fc8e60728e012a3ae043249a7619ec7/src/components/tabs/infinity-dimensions/ModernInfinityDimensionRow.vue#L99

However, the way the local variable is initialized causes this update to also affect the not-so-local `InfinityDimensions.HARDCAP_PURCHASES` variable upstream, as the two are linked.
Thus, `InfinityDimensions.HARDCAP_PURCHASES` is set to the total cap on purchases, which is equal to what it was before plus the bonus from Tesseracts.

This repeats for all Infinity Dimensions which are capped on purchases.

**This affects game balance, making Infinity Dimensions overpowered and this making it very easy to reach END even outside Doomed Realities.**

**Comment by HexaVault** [comment]
fixed by not setting the hardcap value to equal the variable to begin with (which is bad practice when using vue), closing this and pr
