### ISSUE TITLE
Galaxy Generator: still can't drain rifts and progress to END without crashing

### ISSUE THREAD

**Issue by James103** [HexaVault/AD-breaketernity#30]
**Describe the bug**
The Galaxy Generator throws a `this.capRift.reducedTo.sub is not a function` error when attempting to drain Rifts to increase the cap, here: https://github.com/HexaVault/AD-breaketernity/blob/857b8fdd00c37627a4a2b3e0b6f57eea31a68cf8/src/core/celestials/pelle/galaxy-generator.js#L70

**To Reproduce**
1. Unlock the Galaxy Generator.
2. Upgrade it and wait for the generated galaxies to reach the first threshold.
3. Use the Galaxy Generator to drain a Rift, to try to increase the cap.
4. The game crashes.

**Expected behavior**
Draining Rifts through the Galaxy Generator should not crash or throw an error.

**Savefile**
[save2.txt](https://github.com/user-attachments/files/16244010/save2.txt)

**Additional context**
https://github.com/HexaVault/AD-breaketernity/pull/26 attempted to fix this issue, but it was closed because the relevant code has "already changed on my end, just not pushed (no need to push the same thing twice)." The fix that was pushed only fixed the case of the Galaxy Generator anti-draining Rifts during its final phase, not the case described here.
See: https://github.com/HexaVault/AD-breaketernity/commit/aedbda29634d240064e2318603fc650787838361#diff-23d5dc9e5e0874e9195dcac4c2cd90ecf13d341b861eeace500365f72f995703R105

**Comment by HexaVault** [comment]
Yeah, seems i missed the other change when i was writing in your commit manually into mine (to prevent issues)

**Comment by James103** [comment]
I can no longer reproduce this error; it appears to be fixed.
