### ISSUE TITLE
2 Bugs of [Implicit conversion from Decimal to number] 

### ISSUE THREAD

**Issue by Chara1912** [HexaVault/AD-breaketernity#33]
**Describe the bug**
I. [Implicit conversion from Decimal to number] Opening Celestial Navigation.
II. [Implicit conversion from Decimal to number]  Antimatter Galaxies disappear when reaching Remote (800 or 100K after RU51)

**To Reproduce**
1: Complete r147 and open Celestial Navigation.
2: Reach 800 Antimatter Galaxies.

**Expected behavior**
1: Celestial Navigation will be open normally.
2: Antimatter Galaxies in AD tab still exist after reaching Remote AG.

**Screenshots**
![image](https://github.com/user-attachments/assets/0f512495-0b81-49a6-b0a7-4e9afe34b69b)
![image](https://github.com/user-attachments/assets/b92d3da6-e0ce-4b77-b939-3f9d05c15488)

**Savefile**
[ADBUG(800AG+r147).txt](https://github.com/user-attachments/files/16570628/ADBUG.800AG%2Br147.txt)

**Additional context**
None

**Comment by James103** [comment]
I can still reproduce both errors in 6386514e958fd9e4347cb805e7861fefe4d688b1.

Stack trace for Remote Antimatter Galaxy error (Classic theme):
```
07:00:22.690 Error: Implicit conversion from Decimal to number
    valueOf extensions.js:263
    costScalingText ClassicAntimatterGalaxyRow.vue:78
    getter ui.js:87
    VueJS 4
    render ClassicAntimatterGalaxyRow.vue:32
    VueJS 51
    show tabs.js:155
    show tabs.js:50
    click ClassicSubtabButton.vue:11
    VueJS 33
vue.runtime.esm.js:3065
```

No such error is present in Modern theme.

Stack trace for Celestial Navigation error:
```
07:00:36.610 Error: Implicit conversion from Decimal to number
    valueOf extensions.js:263
    depressedQuarticRealRoots math.js:1053
    solveSimpleBiquadratic math.js:1113
    fitCurveSection math.js:1463
    single math.js:1590
    cubicBezierFitToCurveSection math.js:1604
    getOffsetPath ProgressConnector.vue:147
    generateIncompletePath ProgressConnector.vue:136
    incompleteFadePath ProgressConnector.vue:102
    getter ui.js:87
    VueJS 4
    render ProgressConnector.vue:8
    VueJS 43
    show tabs.js:154
    click ClassicTabButton.vue:15
    VueJS 33
vue.runtime.esm.js:3065
```

**Comment by glitchyfishys** [comment]
the classic AD tab should be fixed by this
`scalings.sort((a, b) => a.amount.gt(b.amount) -1)`
and the celestial navigation may be Lai'tela unlocks are using Math like this one
`Math.min(upgrade.currency.value, upgrade.cost)`
and in testing I found `maxAllDMDimensions(maxTier)` autobuyer breaks if you have singularity milestones as the maxTier is higher than the unlocked ones

**Comment by HexaVault** [comment]
purchasing upgrades for dmds that arent unlocked shouldnt throw an error?

**Comment by HexaVault** [comment]
also max tier shoulsnt go above 4, but ill add extra checks if i have some form of save for testing this bug

**Comment by HexaVault** [comment]
additionally, to actually speak about the bug, i will be able start fixing up the port in a couple of days so it should be fixed sometime next week

**Comment by glitchyfishys** [comment]
> also max tier shoulsnt go above 4, but ill add extra checks if i have some form of save for testing this bug

not that is goes above 4, just that unlocked < auto max unlocked
