### ISSUE TITLE
Fatal Bug: Game Can't Open

### ISSUE THREAD

**Issue by antimatter19728** [HexaVault/AD-breaketernity#43]
**Describe the bug**
[My mod](https://github.com/antimatter19728/My-AD-Mods/tree/main/ng-plus) have a bug(game can't open)

**To Reproduce**
`
npm ci
npm run serve
`

**Expected behavior**
game can't open

**Screenshots**
![2](https://github.com/user-attachments/assets/73b0d2a3-e934-42d9-b5f4-16ac67aaba6e)

**Comment by HexaVault** [comment]
1. Please do not ping us. We can see the issues tab as is
2. This is because you have incorrectly called something, or imported something instead of just calling it. This is not a fault of the port, and therefore we cannot do anything about this, so being closed.
