### ISSUE TITLE
`player.records.realTimePlayed` is reactive - error spam from Statistics tab

### ISSUE THREAD

**Issue by James103** [HexaVault/AD-breaketernity#9]
Exactly as it is in the title: opening the Statistics tab results in `Error: player.records.realTimePlayed became REACTIVE` being thrown every tick.

**Comment by Donaldino7712** [comment]
from my testing it doesn't actually break the tab, but it's just that the error is thrown every tick

**Comment by Donaldino7712** [comment]
Fixed in https://github.com/HexaVault/AD-breaketernity/commit/96789c2621743db3e96696d17e06d5a5dc4d747a
